import { migrate1 } from './migrate1.js';
import { migrate2 } from './migrate2.js';
import { migrate3 } from './migrate3.js';
import { migrate4 } from './migrate4.js';
import { migrate5 } from './migrate5.js';
import { migrate6 } from './migrate6.js';
import { migrate7 } from './migrate7.js';
import { migrate8 } from './migrate8.js';
import { migrate9 } from './migrate9.js';
import { migrate10 } from './migrate10.js';
import { migrate11 } from './migrate11.js';
import { migrate12 } from './migrate12.js';
import { migrate13 } from './migrate13.js';
import { migrate14 } from './migrate14.js';
import { migrate15 } from './migrate15.js';
import { migrate16 } from './migrate16.js';
import { migrate17 } from './migrate17.js';
import { migrate18 } from './migrate18.js';
import { migrate19 } from './migrate19.js';
import { migrate20 } from './migrate20.js';
import { migrate21 } from './migrate21.js';
import { migrate22 } from './migrate22.js';
import { migrate23 } from './migrate23.js';
import { migrate24 } from './migrate24.js';
import { migrate25 } from './migrate25.js';
import { migrate26 } from './migrate26.js';
import { migrate27 } from './migrate27.js';
import { migrate28 } from './migrate28.js';
import { migrate29 } from './migrate29.js';
import { migrate30 } from './migrate30.js';
import { migrate31 } from './migrate31.js';
import { migrate32 } from './migrate32.js';
import { migrate33 } from './migrate33.js';
import { migrate34 } from './migrate34.js';
import { migrate35 } from './migrate35.js';
import { migrate36 } from './migrate36.js';
import { migrate37 } from './migrate37.js';
import { migrate38 } from './migrate38.js';
import { migrate39 } from './migrate39.js';
import { migrate40 } from './migrate40.js';
import { migrate41 } from './migrate41.js';
import { migrate42 } from './migrate42.js';
import { migrate43 } from './migrate43.js';
import { migrate44 } from './migrate44.js';
import { migrate45 } from './migrate45.js';
import { migrate46 } from './migrate46.js';
import { migrate47 } from './migrate47.js';
import { migrate48 } from './migrate48.js';
import { migrate49 } from './migrate49.js';
import { migrate50 } from './migrate50.js';

export const migrations = [
  { version: 1, up: migrate1 },
  { version: 2, up: migrate2 },
  { version: 3, up: migrate3 },
  { version: 4, up: migrate4 },
  { version: 5, up: migrate5 },
  { version: 6, up: migrate6 },
  { version: 7, up: migrate7 },
  { version: 8, up: migrate8 },
  { version: 9, up: migrate9 },
  { version: 10, up: migrate10 },
  { version: 11, up: migrate11 },
  { version: 12, up: migrate12 },
  { version: 13, up: migrate13 },
  { version: 14, up: migrate14 },
  { version: 15, up: migrate15 },
  { version: 16, up: migrate16 },
  { version: 17, up: migrate17 },
  { version: 18, up: migrate18 },
  { version: 19, up: migrate19 },
  { version: 20, up: migrate20 },
  { version: 21, up: migrate21 },
  { version: 22, up: migrate22 },
  { version: 23, up: migrate23 },
  { version: 24, up: migrate24 },
  { version: 25, up: migrate25 },
  { version: 26, up: migrate26 },
  { version: 27, up: migrate27 },
  { version: 28, up: migrate28 },
  { version: 29, up: migrate29 },
  { version: 30, up: migrate30 },
  { version: 31, up: migrate31 },
  { version: 32, up: migrate32 },
  { version: 33, up: migrate33 },
  { version: 34, up: migrate34 },
  { version: 35, up: migrate35 },
  { version: 36, up: migrate36 },
  { version: 37, up: migrate37 },
  { version: 38, up: migrate38 },
  { version: 39, up: migrate39 },
  { version: 40, up: migrate40 },
  { version: 41, up: migrate41 },
  { version: 42, up: migrate42 },
  { version: 43, up: migrate43 },
  { version: 44, up: migrate44 },
  { version: 45, up: migrate45 },
  { version: 46, up: migrate46 },
  { version: 47, up: migrate47 },
  { version: 48, up: migrate48 },
  { version: 49, up: migrate49 },
  { version: 50, up: migrate50 },
];
